version: '3'

services:
  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    restart: always 
    networks:
      - network-backend
      - network-frontend

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: always 
    networks:
      - network-frontend
  
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: galoperidolnaya
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always 
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend:

volumes:
  postgres: