version: '3'

services:
  backend:
    build: ./backend
    environment:
      - CONNECTION_STRING=postgres://root:password@db/galoperidolnaya
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: always 
    networks:
      - network-backend
      - network-frontend

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: always 
    networks:
      - network-frontend
  
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: galoperidolnaya
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    restart: always 
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend: