version: '3.9'
volumes:
  postgres_data:

services:
  zarya-app:
    container_name: zarya-app
    depends_on:
      - zarya-db
    build: .
    ports:
      - 7000:7000
    env_file:
      - .env
    networks:
      zarya-network:

  zarya-db:
    container_name: zarya-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPORT: ${DB_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      zarya-network:
        aliases: 
          - zarya.db.loc

networks:
  zarya-network: